services:
  - type: web
    name: placement-predictor-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: DB_NAME
        value: placement_db
